### ISSUE TITLE
pa11y fails when running in GitHub

### ISSUE THREAD

**Issue by cannandev** [18F/accessibility#316]
Throws this error... 

```shell
Run npm run pa11y-ci:sitemap
> pa11y-ci:sitemap
> pa11y-ci --sitemap http://localhost:[4](https://github.com/18F/accessibility/runs/7009213621?check_suite_focus=true#step:6:5)000/sitemap.xml --sitemap-exclude "/*.pdf"
Running Pa11y on 23 URLs:
 > http://localhost:4000/css/ - 0 errors
 > http://localhost:4000/alternative-versions/ - 0 errors
 > http://localhost:4000/checklist/ - 0 errors
 > http://localhost:4000/color/ - 0 errors
 > http://localhost:4000/gov-resources/ - 0 errors
 > http://localhost:4000/flashing/ - 0 errors
 > http://localhost:4000/headings/ - 0 errors
 > http://localhost:4000/forms/ - 0 errors
/home/runner/work/accessibility/accessibility/node_modules/puppeteer/lib/Page.js:21[5](https://github.com/18F/accessibility/runs/7009213621?check_suite_focus=true#step:6:6)
    this.emit('error', new Error('Page crashed!'));
                       ^
Error: Page crashed!
    at Page._onTargetCrashed (/home/runner/work/accessibility/accessibility/node_modules/puppeteer/lib/Page.js:215:24)
    at CDPSession.<anonymous> (/home/runner/work/accessibility/accessibility/node_modules/puppeteer/lib/Page.js:123:5[6](https://github.com/18F/accessibility/runs/7009213621?check_suite_focus=true#step:6:7))
    at CDPSession.emit (node:events:52[7](https://github.com/18F/accessibility/runs/7009213621?check_suite_focus=true#step:6:8):2[8](https://github.com/18F/accessibility/runs/7009213621?check_suite_focus=true#step:6:9))
    at CDPSession._onMessage (/home/runner/work/accessibility/accessibility/node_modules/puppeteer/lib/Connection.js:200:12)
    at Connection._onMessage (/home/runner/work/accessibility/accessibility/node_modules/puppeteer/lib/Connection.js:112:17)
    at WebSocket.<anonymous> (/home/runner/work/accessibility/accessibility/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
    at WebSocket.onMessage (/home/runner/work/accessibility/accessibility/node_modules/ws/lib/event-target.js:120:16)
    at WebSocket.emit (node:events:527:28)
    at Receiver.receiverOnMessage (/home/runner/work/accessibility/accessibility/node_modules/ws/lib/websocket.js:78[9](https://github.com/18F/accessibility/runs/7009213621?check_suite_focus=true#step:6:10):20)
    at Receiver.emit (node:events:527:28)
Emitted 'error' event on Page instance at:
    at Page._onTargetCrashed (/home/runner/work/accessibility/accessibility/node_modules/puppeteer/lib/Page.js:215:[10](https://github.com/18F/accessibility/runs/7009213621?check_suite_focus=true#step:6:11))
    at CDPSession.<anonymous> (/home/runner/work/accessibility/accessibility/node_modules/puppeteer/lib/Page.js:[12](https://github.com/18F/accessibility/runs/7009213621?check_suite_focus=true#step:6:13)3:56)
    [... lines matching original stack trace ...]
    at Receiver.emit (node:events:5[27](https://github.com/18F/accessibility/runs/7009213621?check_suite_focus=true#step:6:28):[28](https://github.com/18F/accessibility/runs/7009213621?check_suite_focus=true#step:6:29))
Error: Process completed with exit code 1.
```

**Comment by christophermather** [comment]
I _believe_ this is no longer an issue. Plus, it appears we may move away from pa11y in the future: https://github.com/18F/TLC-crew/issues/501

Closing.
